POST http://0.0.0.0:8080/register
Content-Type: application/json

{
  "id": "739d6241-2f2c-4908-b1bd-e7c9540d36a1",
  "name": "ucup",
  "email": "eail@example.com",
  "password": "$2a$10$koOVCqgas1pIzEofexmFAeOXeL1PhKWCCFFX9oH1sX/rxVmBamTIS"
}
###

POST http://0.0.0.0:8080/login
Content-Type: application/json

{
  "email": "milly.hoppe@hotmail.test",
  "password": "password"
}
###

GET http://0.0.0.0:8080/logout
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwic2Vzc2lvbiI6IjhlZTQ0NjMyLWI3MjAtNGI3NC04ODFjLWJhNTAwMzNlZGNlZCIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAvIiwidmVyaWZpZWQiOnRydWUsImV4cCI6MTY1OTQyNjk0MywidXNlciI6ImMzODcyMzEyLTc4ODQtNDJmNi04NDQ5LWYxNDZhYWQzMmY5ZiJ9.TwSIdkOLScOWd8CvtV0_d1EfReVhEpyRI8HkHgXKex4

###



