GET http://0.0.0.0:8080/room/15bb3a88-5ada-489e-98b4-491ea898b9b6/room-info
Content-Type: application/json
###

GET http://0.0.0.0:8080/room/15bb3a88-5ada-489e-98b4-491ea898b9b6/room-info
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwic2Vzc2lvbiI6ImViNTU2YTcyLTA3ZGYtNGRjMC1hNzBmLWE4NGY4YmRlMGM3NCIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAvIiwidmVyaWZpZWQiOmZhbHNlLCJleHAiOjE2NjEwODc5NTMsInVzZXIiOiI3MzlkNjI0MS0yZjJjLTQ5MDgtYjFiZC1lN2M5NTQwZDM2NDMifQ.fvmNXDWpZtaDubtmoscKddHPRNQGrzcQWqOwqVkyE28
Content-Type: application/json
###
GET http://0.0.0.0:8080/room/tenant
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwic2Vzc2lvbiI6Ijk3YjI1N2U5LTcwNzctNGJiNS04ZjhmLTM3Y2RiYTZkMDVmZCIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAvIiwidmVyaWZpZWQiOnRydWUsImV4cCI6MTY2MTA4ODM2OSwidXNlciI6IjczOWQ2MjQxLTJmMmMtNDkwOC1iMWJkLWU3Yzk1NDBkMzY0MyJ9.46hKssw8x6QWu6qUOpWupBGAtXmPIQsBSBqeo4fd0SA
Content-Type: application/json
###
GET http://0.0.0.0:8080/room/15bb3a88-5ada-489e-98b4-491ea898b9b6/rule
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwic2Vzc2lvbiI6ImIxNmE0Y2MwLTZiZjItNDJjZi05NmNmLTU0YWE4NDRmNWExZCIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAvIiwidmVyaWZpZWQiOmZhbHNlLCJleHAiOjE2NjEwODQwNTUsInVzZXIiOiIxMGQ1OWJiMy01ZDJkLTQ2ZGItOTZiYy04NDg5MTgwMjZmYTAifQ.7XhkoUlndeMsJ55jnl-gngIYwUZrA2SUkWPn8w_pZ68
Content-Type: application/json
###
GET http://0.0.0.0:8080/room/15bb3a88-5ada-489e-98b4-491ea898b9b6/reminder
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwic2Vzc2lvbiI6ImIxNmE0Y2MwLTZiZjItNDJjZi05NmNmLTU0YWE4NDRmNWExZCIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAvIiwidmVyaWZpZWQiOmZhbHNlLCJleHAiOjE2NjEwODQwNTUsInVzZXIiOiIxMGQ1OWJiMy01ZDJkLTQ2ZGItOTZiYy04NDg5MTgwMjZmYTAifQ.7XhkoUlndeMsJ55jnl-gngIYwUZrA2SUkWPn8w_pZ68
Content-Type: application/json
###
GET http://0.0.0.0:8080/room/15bb3a88-5ada-489e-98b4-491ea898b9b6/reminder-date
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwic2Vzc2lvbiI6ImIxNmE0Y2MwLTZiZjItNDJjZi05NmNmLTU0YWE4NDRmNWExZCIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAvIiwidmVyaWZpZWQiOmZhbHNlLCJleHAiOjE2NjEwODQwNTUsInVzZXIiOiIxMGQ1OWJiMy01ZDJkLTQ2ZGItOTZiYy04NDg5MTgwMjZmYTAifQ.7XhkoUlndeMsJ55jnl-gngIYwUZrA2SUkWPn8w_pZ68
Content-Type: application/json
###
GET http://0.0.0.0:8080/room/15bb3a88-5ada-489e-98b4-491ea898b9b6/reminder-date-range
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwic2Vzc2lvbiI6ImIxNmE0Y2MwLTZiZjItNDJjZi05NmNmLTU0YWE4NDRmNWExZCIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAvIiwidmVyaWZpZWQiOmZhbHNlLCJleHAiOjE2NjEwODQwNTUsInVzZXIiOiIxMGQ1OWJiMy01ZDJkLTQ2ZGItOTZiYy04NDg5MTgwMjZmYTAifQ.7XhkoUlndeMsJ55jnl-gngIYwUZrA2SUkWPn8w_pZ68
Content-Type: application/json
###
GET http://0.0.0.0:8080/room/tenant
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwic2Vzc2lvbiI6IjZiNzI3YmQxLWY4ZTUtNGQxNi1hNGJmLWQ5MjZkNGY1YzhhMyIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAvIiwidmVyaWZpZWQiOnRydWUsImV4cCI6MTY2MTA4NTczNywidXNlciI6Ijc2Zjc2YzQ1LTYxZGYtNGE3ZC1hNGYzLTEwZjA2YjAzMjAzZiJ9.aPx2cJolCJiS7VgXiLSFbasPIdMWEteoNc5lmH8jKKQ
Content-Type: application/json
###
